#!/usr/bin/env python3
"""
Script: 04_generate_final_report.py
Purpose: Generate comprehensive final report for differential analysis
Author: DreaMS Workflow
Date: 2026-01-10
"""

import sys
import pandas as pd
import numpy as np
from pathlib import Path
from collections import Counter
from datetime import datetime

# Add DreaMS to path
sys.path.append('/stor1/aims4dc/aims4dc_scripts/DreaMS')


class DifferentialReportGenerator:
    """Generate comprehensive differential analysis report"""

    def __init__(self, results_dir: str):
        """
        Initialize report generator

        Args:
            results_dir: Directory containing all analysis results
        """
        self.results_dir = Path(results_dir)

    def load_results(self):
        """Load all analysis results"""
        print("Loading analysis results...")

        # Identified compounds
        identified_file = self.results_dir / 'FINAL_DIFFERENTIAL_COMPOUNDS_IDENTIFIED.csv'
        if identified_file.exists():
            self.identified = pd.read_csv(identified_file)
            print(f"  Loaded {len(self.identified)} identified compounds")
        else:
            print(f"  ⚠ Identified compounds file not found")
            self.identified = None

        # Unique compounds
        unique_a_file = self.results_dir / 'statistics' / 'unique_to_authentic.csv'
        unique_b_file = self.results_dir / 'statistics' / 'unique_to_counterfeit.csv'

        if unique_a_file.exists():
            self.unique_a = pd.read_csv(unique_a_file)
            print(f"  Loaded {len(self.unique_a)} authentic-specific compounds")
        else:
            self.unique_a = None

        if unique_b_file.exists():
            self.unique_b = pd.read_csv(unique_b_file)
            print(f"  Loaded {len(self.unique_b)} counterfeit-specific compounds")
        else:
            self.unique_b = None

        # Metadata
        metadata_file = self.results_dir / 'spectrum_metadata.csv'
        if metadata_file.exists():
            self.metadata = pd.read_csv(metadata_file)
            print(f"  Loaded metadata for {len(self.metadata)} spectra")
        else:
            self.metadata = None

    def generate_comprehensive_report(self):
        """Generate comprehensive text report"""
        print("\n=== Generating Comprehensive Report ===")

        report = []
        report.append("=" * 80)
        report.append("中药正品与伪品差异化合物分析综合报告")
        report.append("Traditional Chinese Medicine: Authentic vs Counterfeit")
        report.append("Differential Compound Analysis Report")
        report.append("=" * 80)
        report.append("")
        report.append(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append(f"Generated by: DreaMS Differential Analysis Workflow")
        report.append("")

        # Section 1: Dataset Overview
        report.append("=" * 80)
        report.append("1. DATASET OVERVIEW")
        report.append("=" * 80)
        report.append("")

        if self.metadata is not None:
            group_a_count = len(self.metadata[self.metadata['group'] == 'A'])
            group_b_count = len(self.metadata[self.metadata['group'] == 'B'])

            report.append(f"Total spectra analyzed: {len(self.metadata)}")
            report.append(f"  - Group A (Authentic/正品): {group_a_count} spectra")
            report.append(f"  - Group B (Counterfeit/伪品): {group_b_count} spectra")
            report.append("")

        # Section 2: Statistical Summary
        report.append("=" * 80)
        report.append("2. STATISTICAL SUMMARY")
        report.append("=" * 80)
        report.append("")

        if self.unique_a is not None and self.unique_b is not None:
            report.append(f"Differential compounds identified:")
            report.append(f"  - Authentic-specific markers (正品特有标志物): {len(self.unique_a)}")
            report.append(f"  - Counterfeit-specific markers (伪品特有标志物): {len(self.unique_b)}")
            report.append("")

        if self.identified is not None:
            successfully_identified = len(self.identified[self.identified['compound_name'].notna()])
            report.append(f"Structure identification success:")
            report.append(f"  - Successfully identified: {successfully_identified} compounds")
            report.append(f"  - Identification rate: {successfully_identified/len(self.identified)*100:.1f}%")
            report.append("")

        # Section 3: Top Authentic Markers
        report.append("=" * 80)
        report.append("3. TOP AUTHENTIC MARKERS (正品标志化合物)")
        report.append("=" * 80)
        report.append("")
        report.append("These compounds should be PRESENT in authentic samples")
        report.append("这些化合物应该在正品中存在")
        report.append("")

        if self.identified is not None:
            authentic_markers = self.identified[
                self.identified['differential_type'] == 'Authentic-specific (正品特有)'
            ].sort_values('differential_specificity', ascending=False).head(10)

            if len(authentic_markers) > 0:
                for i, (idx, row) in enumerate(authentic_markers.iterrows(), 1):
                    report.append(f"{i}. {row.get('compound_name', 'Unknown')}")
                    report.append(f"   Precursor m/z: {row.get('precursor_mz', 0):.4f}")

                    if pd.notna(row.get('molecular_formula')):
                        report.append(f"   Molecular formula: {row['molecular_formula']}")
                    if pd.notna(row.get('smiles')):
                        report.append(f"   SMILES: {row['smiles']}")
                    if pd.notna(row.get('source_database')):
                        report.append(f"   Database source: {row['source_database']}")
                    if pd.notna(row.get('identification_score')):
                        report.append(f"   Identification score: {row['identification_score']:.3f}")
                    if pd.notna(row.get('differential_specificity')):
                        report.append(f"   Differential specificity: {row['differential_specificity']:.3f}")
                    report.append("")
            else:
                report.append("  No identified authentic markers")
                report.append("")
        elif self.unique_a is not None:
            for i, (idx, row) in enumerate(self.unique_a.head(10).iterrows(), 1):
                report.append(f"{i}. {row.get('name', 'Unknown')}")
                report.append(f"   Precursor m/z: {row.get('precursor_mz', 0):.4f}")
                report.append(f"   Retention time: {row.get('retention_time', 0):.2f} min")
                report.append(f"   Specificity score: {row.get('specificity', 0):.3f}")
                report.append("")

        # Section 4: Top Counterfeit Markers
        report.append("=" * 80)
        report.append("4. TOP COUNTERFEIT MARKERS (伪品标志化合物)")
        report.append("=" * 80)
        report.append("")
        report.append("These compounds should NOT be present in authentic samples")
        report.append("这些化合物不应该在正品中存在")
        report.append("")

        if self.identified is not None:
            counterfeit_markers = self.identified[
                self.identified['differential_type'] == 'Counterfeit-specific (伪品特有)'
            ].sort_values('differential_specificity', ascending=False).head(10)

            if len(counterfeit_markers) > 0:
                for i, (idx, row) in enumerate(counterfeit_markers.iterrows(), 1):
                    report.append(f"{i}. {row.get('compound_name', 'Unknown')}")
                    report.append(f"   Precursor m/z: {row.get('precursor_mz', 0):.4f}")

                    if pd.notna(row.get('molecular_formula')):
                        report.append(f"   Molecular formula: {row['molecular_formula']}")
                    if pd.notna(row.get('smiles')):
                        report.append(f"   SMILES: {row['smiles']}")
                    if pd.notna(row.get('source_database')):
                        report.append(f"   Database source: {row['source_database']}")
                    if pd.notna(row.get('identification_score')):
                        report.append(f"   Identification score: {row['identification_score']:.3f}")
                    if pd.notna(row.get('differential_specificity')):
                        report.append(f"   Differential specificity: {row['differential_specificity']:.3f}")
                    report.append("")
            else:
                report.append("  No identified counterfeit markers")
                report.append("")
        elif self.unique_b is not None:
            for i, (idx, row) in enumerate(self.unique_b.head(10).iterrows(), 1):
                report.append(f"{i}. {row.get('name', 'Unknown')}")
                report.append(f"   Precursor m/z: {row.get('precursor_mz', 0):.4f}")
                report.append(f"   Retention time: {row.get('retention_time', 0):.2f} min")
                report.append(f"   Specificity score: {row.get('specificity', 0):.3f}")
                report.append("")

        # Section 5: Chemical Classification
        report.append("=" * 80)
        report.append("5. CHEMICAL CLASSIFICATION ANALYSIS")
        report.append("=" * 80)
        report.append("")

        if self.identified is not None and 'compound_class' in self.identified.columns:
            # Authentic markers classification
            auth_classes = self.identified[
                self.identified['differential_type'] == 'Authentic-specific (正品特有)'
            ]['compound_class'].value_counts().head(5)

            if len(auth_classes) > 0:
                report.append("Top chemical classes in authentic markers:")
                for cls, count in auth_classes.items():
                    report.append(f"  - {cls}: {count} compounds")
                report.append("")

            # Counterfeit markers classification
            count_classes = self.identified[
                self.identified['differential_type'] == 'Counterfeit-specific (伪品特有)'
            ]['compound_class'].value_counts().head(5)

            if len(count_classes) > 0:
                report.append("Top chemical classes in counterfeit markers:")
                for cls, count in count_classes.items():
                    report.append(f"  - {cls}: {count} compounds")
                report.append("")
        else:
            report.append("Chemical classification data not available")
            report.append("")

        # Section 6: Authentication Recommendations
        report.append("=" * 80)
        report.append("6. AUTHENTICATION RECOMMENDATIONS (鉴别建议)")
        report.append("=" * 80)
        report.append("")
        report.append("Based on this analysis, the following markers are recommended")
        report.append("for authenticating samples:")
        report.append("")

        report.append("A. POSITIVE MARKERS (should be present in authentic):")
        report.append("   正品鉴别指标(应该存在):")
        report.append("")

        if self.unique_a is not None and len(self.unique_a) > 0:
            for i, (idx, row) in enumerate(self.unique_a.head(5).iterrows(), 1):
                compound_name = row.get('name', f"Feature m/z {row.get('precursor_mz', 0):.4f}")
                report.append(f"   {i}. {compound_name}")
                report.append(f"      m/z: {row.get('precursor_mz', 0):.4f}")
                report.append(f"      RT: {row.get('retention_time', 0):.2f} min")
                report.append("")

        report.append("B. NEGATIVE MARKERS (should NOT be present in authentic):")
        report.append("   伪品排除指标(不应该存在):")
        report.append("")

        if self.unique_b is not None and len(self.unique_b) > 0:
            for i, (idx, row) in enumerate(self.unique_b.head(5).iterrows(), 1):
                compound_name = row.get('name', f"Feature m/z {row.get('precursor_mz', 0):.4f}")
                report.append(f"   {i}. {compound_name}")
                report.append(f"      m/z: {row.get('precursor_mz', 0):.4f}")
                report.append(f"      RT: {row.get('retention_time', 0):.2f} min")
                report.append("")

        # Section 7: Quality Control Procedure
        report.append("=" * 80)
        report.append("7. SUGGESTED QUALITY CONTROL PROCEDURE")
        report.append("=" * 80)
        report.append("")
        report.append("Recommended LC-MS/MS-based authentication workflow:")
        report.append("")
        report.append("1. Sample Preparation:")
        report.append("   - Extract sample using standard protocol")
        report.append("   - Use same extraction method as this analysis")
        report.append("")
        report.append("2. LC-MS/MS Analysis:")
        report.append("   - Use same chromatographic and MS conditions")
        report.append("   - Monitor the m/z and RT values listed above")
        report.append("")
        report.append("3. Authentication Criteria:")
        report.append("   - Sample is AUTHENTIC if:")
        report.append("     • ≥3 positive markers detected")
        report.append("     • No negative markers detected")
        report.append("")
        report.append("   - Sample is COUNTERFEIT if:")
        report.append("     • <2 positive markers detected")
        report.append("     • OR ≥1 negative marker detected")
        report.append("")
        report.append("   - Sample is UNCERTAIN if:")
        report.append("     • 2 positive markers detected")
        report.append("     • AND no negative markers detected")
        report.append("     → Recommend additional testing")
        report.append("")

        # Footer
        report.append("=" * 80)
        report.append("END OF REPORT")
        report.append("=" * 80)
        report.append("")
        report.append("Generated by DreaMS Differential Analysis Workflow")
        report.append("For questions or support, refer to DreaMS documentation")
        report.append("")

        # Save report
        report_text = "\n".join(report)
        report_path = self.results_dir / 'COMPREHENSIVE_DIFFERENTIAL_REPORT.txt'

        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report_text)

        print(f"  Saved comprehensive report: {report_path}")

        return report_path, report_text

    def generate_excel_summary(self):
        """Generate Excel summary with multiple sheets"""
        print("\n=== Generating Excel Summary ===")

        excel_path = self.results_dir / 'DIFFERENTIAL_ANALYSIS_SUMMARY.xlsx'

        with pd.ExcelWriter(excel_path, engine='openpyxl') as writer:
            # Sheet 1: Overview
            overview_data = {
                'Category': [],
                'Count': [],
                'Description': []
            }

            if self.metadata is not None:
                overview_data['Category'].append('Total Spectra')
                overview_data['Count'].append(len(self.metadata))
                overview_data['Description'].append('Total MS/MS spectra analyzed')

                overview_data['Category'].append('Group A (Authentic)')
                overview_data['Count'].append(len(self.metadata[self.metadata['group'] == 'A']))
                overview_data['Description'].append('Authentic sample spectra')

                overview_data['Category'].append('Group B (Counterfeit)')
                overview_data['Count'].append(len(self.metadata[self.metadata['group'] == 'B']))
                overview_data['Description'].append('Counterfeit sample spectra')

            if self.unique_a is not None:
                overview_data['Category'].append('Authentic Markers')
                overview_data['Count'].append(len(self.unique_a))
                overview_data['Description'].append('Compounds specific to authentic samples')

            if self.unique_b is not None:
                overview_data['Category'].append('Counterfeit Markers')
                overview_data['Count'].append(len(self.unique_b))
                overview_data['Description'].append('Compounds specific to counterfeit samples')

            df_overview = pd.DataFrame(overview_data)
            df_overview.to_excel(writer, sheet_name='Overview', index=False)

            # Sheet 2: Authentic Markers
            if self.unique_a is not None:
                self.unique_a.to_excel(writer, sheet_name='Authentic_Markers', index=False)

            # Sheet 3: Counterfeit Markers
            if self.unique_b is not None:
                self.unique_b.to_excel(writer, sheet_name='Counterfeit_Markers', index=False)

            # Sheet 4: Identified Compounds (top results)
            if self.identified is not None:
                top_identified = self.identified.sort_values(
                    'differential_specificity', ascending=False
                ).head(100)
                top_identified.to_excel(writer, sheet_name='Top_Identified', index=False)

        print(f"  Saved Excel summary: {excel_path}")

        return excel_path

    def run(self):
        """Run complete report generation"""
        print("=" * 80)
        print("DreaMS Differential Analysis - Step 4: Final Report Generation")
        print("=" * 80)

        # Load results
        self.load_results()

        # Generate comprehensive text report
        report_path, report_text = self.generate_comprehensive_report()

        # Generate Excel summary
        excel_path = self.generate_excel_summary()

        # Print report to console
        print("\n" + "=" * 80)
        print("COMPREHENSIVE REPORT")
        print("=" * 80)
        print(report_text)

        # Final summary
        print("\n" + "=" * 80)
        print("✓ Final report generation complete!")
        print("=" * 80)
        print("\nOutput files:")
        print(f"  - Comprehensive report: {report_path}")
        print(f"  - Excel summary: {excel_path}")
        print(f"  - Identified compounds: {self.results_dir / 'FINAL_DIFFERENTIAL_COMPOUNDS_IDENTIFIED.csv'}")
        print(f"  - Statistics directory: {self.results_dir / 'statistics'}")
        print(f"  - Visualization directory: {self.results_dir / 'visualization'}")
        print()
        print("=" * 80)
        print("DIFFERENTIAL ANALYSIS COMPLETE")
        print("=" * 80)
        print()


def main():
    """Main function"""
    import argparse

    parser = argparse.ArgumentParser(
        description='Generate final comprehensive report for differential analysis'
    )
    parser.add_argument(
        '--results-dir',
        type=str,
        required=True,
        help='Directory containing all analysis results'
    )

    args = parser.parse_args()

    # Generate report
    generator = DifferentialReportGenerator(results_dir=args.results_dir)
    generator.run()


if __name__ == '__main__':
    main()
